DocumentService/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DocumentService.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

DocumentService/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DocumentService.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }

        private readonly DocumentService.Data.ApplicationDbContext _context;

        public IndexModel(DocumentService.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnPostCrothall()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            Globals.CURRENT_USER = "Crothall";
            return RedirectToPage("./Index");
        }

        public IActionResult OnPostHospitalA()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            Globals.CURRENT_USER = "Hospital A";
            return RedirectToPage("./Index");
        }

        public IActionResult OnPostHospitalB()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            Globals.CURRENT_USER = "Hospital B";
            return RedirectToPage("./Index");
        }

        public IActionResult OnPostHospitalC()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            Globals.CURRENT_USER = "Hospital C";
            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostDeleteAllSegmentsAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Segment.RemoveRange(_context.Segment);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostDeleteAllBooksAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Book.RemoveRange(_context.Book);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

DocumentService/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DocumentService.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

DocumentService/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="row" style="height:100%;">
    <div class="col-12" style="height:100%;">
        <form method="post" style="height:100%;">
            <div class="card" style="height:100%;border-radius:0px;">
                <div class="card-header" style="height:49px;"><b>DEVELOPER CONTROL PANEL</b></div>
                <div class="card-body" style="height:100%;">
                    <p class="card-text">
                        You are now logged in as <b>@Globals.CURRENT_USER</b><br /><br />
                        Use the following buttons to switch user :
                        <input type="submit" value="Crothall" asp-page-handler="Crothall" class="btn btn-link" style="padding:0; margin-top: -3px;" /> /
                        <input type="submit" value="Hospital A" asp-page-handler="HospitalA" class="btn btn-link" style="padding:0; margin-top: -3px;" /> /
                        <input type="submit" value="Hospital B" asp-page-handler="HospitalB" class="btn btn-link" style="padding:0; margin-top: -3px;" /> /
                        <input type="submit" value="Hospital C" asp-page-handler="HospitalC" class="btn btn-link" style="padding:0; margin-top: -3px;" /><br />
                        Use the following buttons to delete testing data :
                        <input type="submit" value="Delete All Books" asp-page-handler="DeleteAllBooks" class="btn btn-link" style="padding:0; margin-top: -3px;" /> /
                        <input type="submit" value="Delete All Segments" asp-page-handler="DeleteAllSegments" class="btn btn-link" style="padding:0; margin-top: -3px;" />
                    </p>
                </div>
            </div>
        </form>
    </div>
</div>